<a href="https://colab.research.google.com/github/souzafabio/Shinobi/blob/master/Testes_Facilitador_24_04_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# prompt: importe o pandas e abra o arquivo xlsx no drive

import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/RelTolAlTurma-2024-04-24.xlsx', skiprows=8)

df['CURSO'] = df['CURSO'].astype(str)
df['CENSO'] = df['CENSO'].astype(str)


# prompt: exclua todas as colunas em branco

df.dropna(axis=1, inplace=True)

display (df)


df.info()

,REGIONAL,MUNICÍPIO,CENSO,NOVA U.A.,ESCOLA,CURSO,ESCOLARIDADE,SÉRIE,DESCRIÇÃO,TURMA,...,TOTAL ALUNO EM PROGRESSÃO PARCIAL,SALA DE AULA,TIPO DE GESTÃO,SITUAÇÃO DA TURMA,CARÊNCIA,DURACAO,COMPARTILHADO,SÉRIE CONCLUINTE,NECESSIDADE TOTAL,TEMPOS DE AULA
0,BAIXADAS LITORANEAS,ARARUAMA,33026386,11802301539,CIEP 253 GUIMARÃES ROSA,2.91,"ENSINO MÉDIO ITINERÁRIO DE TECNOLOGIA, SUSTENT...",1,"NEM ITIN. TECNOLOGIA, SUSTENTABILIDADE, ESPORT...",NEM_TSEA-1001,...,0,SL-01,ESTADUAL,COMPLETA,0,50,N,Não,46,10
1,BAIXADAS LITORANEAS,ARARUAMA,33026386,11802301539,CIEP 253 GUIMARÃES ROSA,2.91,"ENSINO MÉDIO ITINERÁRIO DE TECNOLOGIA, SUSTENT...",1,"NEM ITIN. TECNOLOGIA, SUSTENTABILIDADE, ESPORT...",NEM_TSEA-1002,...,0,SL-02,ESTADUAL,COMPLETA,0,50,N,Não,46,10
2,BAIXADAS LITORANEAS,ARARUAMA,33026386,11802301539,CIEP 253 GUIMARÃES ROSA,2.91,"ENSINO MÉDIO ITINERÁRIO DE TECNOLOGIA, SUSTENT...",1,"NEM ITIN. TECNOLOGIA, SUSTENTABILIDADE, ESPORT...",NEM_TSEA-1003,...,0,SL-03,ESTADUAL,COMPLETA,0,50,N,Não,46,10
3,BAIXADAS LITORANEAS,ARARUAMA,33026386,11802301539,CIEP 253 GUIMARÃES ROSA,2.91,"ENSINO MÉDIO ITINERÁRIO DE TECNOLOGIA, SUSTENT...",1,"NEM ITIN. TECNOLOGIA, SUSTENTABILIDADE, ESPORT...",NEM_TSEA-1004,...,0,SL-04,ESTADUAL,COMPLETA,0,50,N,Não,46,10
4,BAIXADAS LITORANEAS,ARARUAMA,33026386,11802301539,CIEP 253 GUIMARÃES ROSA,2.91,"ENSINO MÉDIO ITINERÁRIO DE TECNOLOGIA, SUSTENT...",1,"NEM ITIN. TECNOLOGIA, SUSTENTABILIDADE, ESPORT...",NEM_TSEA-1005,...,0,SL-05,ESTADUAL,COMPLETA,0,50,N,Não,46,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33544,SUL FLUMINENSE,VOLTA REDONDA,33156999,11802303545,CIEP 293 WALMIR DE FREITAS MONTEIRO,2024.02,NEM ITINERÁRIO FORMATIVO DE LINGUAGENS E SUAS ...,2,ENSINO MÉDIO REGULAR - 2ª SÉRIE,IF_LM_2002,...,0,SL-05,ESTADUAL,COMPLETA,1,50,S,Não,30,6
33545,SUL FLUMINENSE,VOLTA REDONDA,33156999,11802303545,CIEP 293 WALMIR DE FREITAS MONTEIRO,2024.05,NEM ITINERÁRIO FORMATIVO DE CIÊNCIAS DA NATURE...,2,ENSINO MÉDIO REGULAR - 2ª SÉRIE,IF_RN_2001,...,0,SL-04,ESTADUAL,COMPLETA,1,50,S,Não,30,6
33546,SUL FLUMINENSE,VOLTA REDONDA,33156999,11802303545,CIEP 293 WALMIR DE FREITAS MONTEIRO,2024.09,NEM ITINERÁRIO FORMATIVO INTEGRAÇÃO DAS ÁREAS ...,2,ENSINO MÉDIO REGULAR - 2ª SÉRIE,IT_GD_2003,...,1,SL-05,ESTADUAL,COMPLETA,2,45,S,Não,30,6
33547,SUL FLUMINENSE,VOLTA REDONDA,33156999,11802303545,CIEP 293 WALMIR DE FREITAS MONTEIRO,9999.01,PROJETO FOCO (PRESENCIAL),1,FOCO PRESENCIAL_PORTUGUÊS_1ª SÉRIE,FOCPOR_1ª_01,...,0,SL-28,ESTADUAL,COMPLETA,0,50,S,Sim,4,6
33548,SUL FLUMINENSE,VOLTA REDONDA,33156999,11802303545,CIEP 293 WALMIR DE FREITAS MONTEIRO,9999.01,PROJETO FOCO (PRESENCIAL),2,FOCO PRESENCIAL_PORTUGUÊS_2ª SÉRIE,FOCPOR_2ª_01,...,0,SL-26,ESTADUAL,COMPLETA,0,50,S,Sim,4,6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33549 entries, 0 to 33548
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   REGIONAL                           33549 non-null  object
 1   MUNICÍPIO                          33549 non-null  object
 2   CENSO                              33549 non-null  object
 3   NOVA U.A.                          33549 non-null  int64
 4   ESCOLA                             33549 non-null  object
 5   CURSO                              33549 non-null  object
 6   ESCOLARIDADE                       33549 non-null  object
 7   SÉRIE                              33549 non-null  int64
 8   DESCRIÇÃO                          33549 non-null  object
 9   TURMA                              33549 non-null  object
 10  NOME TURMA                         33549 non-null  object
 11  SEMESTRE                           33549 non-null  int64
 12  MATRIZ                             33549 non-null  object
 13  TURNO                              33549 non-null  object
 14  TOTAL DE ALUNOS                    33549 non-null  int64
 15  TOTAL ALUNO EM PROGRESSÃO PARCIAL  33549 non-null  int64
 16  SALA DE AULA                       33549 non-null  object
 17  TIPO DE GESTÃO                     33549 non-null  object
 18  SITUAÇÃO DA TURMA                  33549 non-null  object
 19  CARÊNCIA                           33549 non-null  int64
 20  DURACAO                            33549 non-null  int64
 21  COMPARTILHADO                      33549 non-null  object
 22  SÉRIE CONCLUINTE                   33549 non-null  object
 23  NECESSIDADE TOTAL                  33549 non-null  int64
 24  TEMPOS DE AULA                     33549 non-null  int64
dtypes: int64(9), object(16)
memory usage: 6.4+ MB

In [ ]:
# Criar uma lista com os valores a serem excluídos
valores_a_excluir = [".*CEJA.*", "^CURSOS$", "ELETIVA.*", "^EDUCAÇÃO ESPECIAL$", "^PROJETO FOCO.*", ".*SEMIPRESENCIAL.*", "^DE UNIDADES ESCOLARES PRISIONAIS E SOCIOEDUCATIVAS$", "^EJA", ".*JOVENS E ADULTOS.*", ".*ENSINO FUNDAMENTAL.*",
                    "33558221", "33034273", "33035334", "33036519", "33097224", "33096740", "33097607", "33088942",
                    "33088969", "33091323", "33062277", "33068844", "33069026", "33069034", "33069948", "33069956",
                    "33069964", "33070148", "33070156", "33070164", "33070172", "33070199", "33070326", "33071535",
                    "33071543", "33071578", "33071586", "33071616", "33072078", "33072094", "33072183", "33072205",
                    "33072280", "33072370", "33073368", "33074038", "33074046", "33074054", "33074160", "33074232",
                    "33074798", "33075174", "33075182", "33075190", "33075204", "33075220", "33075689", "33075719",
                    "33075760", "33075816", "33075832", "33075867", "33075875", "33075891", "33085463", "33085480",
                    "33085765", "33085838", "33086540", "33086567", "33086575", "33086729", "33086753", "33086796",
                    "33088160", "33088179", "33095078", "33117950", "33124922", "33126259", "33127395", "33140030",
                    "33140049", "33145440", "33062250", "33062293", "33075883", "33079331", "33079382", "33079404",
                    "33079668", "33079692", "33079706", "33079714", "33079722", "33079811", "33079820", "33079900",
                    "33082030", "33082227", "33082251", "33082286", "33082316", "33082324", "33082332", "33082340",
                    "33082359", "33082375", "33082430", "33084459", "33086737", "33100675", "33125341", "33125627",
                    "33127514", "33128600", "33128618", "33136459", "33136483", "33136513", "33136696", "33045437",
                    "33045569", "33166382", "33048347", "33048835", "33097895", "33099189", "33099286", "33110220",
                    "33191280", "33062927", "33063052", "33063400", "33063877", "33064792", "33065292", "33066027",
                    "33066140", "33066612", "33066620", "33067783", "33071560", "33072337", "33077088", "33077118",
                    "33077126", "33077134", "33077142", "33077150", "33077169", "33077177", "33077185", "33077363",
                    "33077371", "33077452", "33077487", "33077495", "33077509", "33077525", "33077568", "33077576",
                    "33086427", "33087725", "33087733", "33087750", "33125805", "33126105", "33126232", "33126941",
                    "33183724", "33518220", "33002126", "33002614", "33003386", "33131163", "33142319", "33518211",
                    "33008272", "33011400", "33093938", "33094128", "33097003", "33100411", "33014736", "33025576",
                    "33012458", "33013160", "33013837", "33013918", "33014086", "33014116", "33014310", "33013535",
                    "33013551", "33013683", "33170185", "33018073", "33042543", "33018367", "33175314", "33019800",
                    "33020205", "33142351", "33021708", "33021937", "33024480", "33149178", "33024880", "33025010",
                    "33036632", "33036713", "33098077", "33098085", "33125449", "33029377", "33029717", "33096864",
                    "33096880", "33166412", "33170169", "33097798", "33032734", "33033099", "33033110", "33033188",
                    "33033196", "33156883", "33156999",
                    "33049734", "33097275", "33046514", "33110476", "33095647", "33033978", "33048339", "33045445", "33096759", "33099758",
                    "33028583", "33099111", "33113319", "33044880", "33097046", "33043515", "33098573", "33058199", "33058458", "33099901",
                    "33058318", "33104638", "33101620", "33046662", "33008299", "33093946", "33041946", "33053340", "33043736", "33105022",
                    "33032718", "33090173", "33001014", "33096830", "33090670", "33099073", "33093024", "33018804", "33027307", "33026386",
                    "33028087", "33028702", "33088950", "33088896", "33096988", "33092168", "33046603", "33094063", "33003386", "33098662"]

#Caso seja necessário remover a PRISIONAL e manter a SOCIOEDUCAÇÃO incluir
#("33170231", "33166366", "33063044", "33063060", "33066124",
#"33079633", "33079838", "33079935", "33136467", "33136491", "33136521", "33146160",
#"33153060", "33170193", "33170215", "33172358", "33228809", "33337217", "33340200")

#Caso seja necessário remover COMPARTILHADAS incluir
# ("33558221", "33034273", "33035334", "33036519", "33097224", "33096740", "33097607", "33088942",
# "33088969", "33091323", "33062277", "33068844", "33069026", "33069034", "33069948", "33069956",
# "33069964", "33070148", "33070156", "33070164", "33070172", "33070199", "33070326", "33071535",
# "33071543", "33071578", "33071586", "33071616", "33072078", "33072094", "33072183", "33072205",
# "33072280", "33072370", "33073368", "33074038", "33074046", "33074054", "33074160", "33074232",
# "33074798", "33075174", "33075182", "33075190", "33075204", "33075220", "33075689", "33075719",
# "33075760", "33075816", "33075832", "33075867", "33075875", "33075891", "33085463", "33085480",
# "33085765", "33085838", "33086540", "33086567", "33086575", "33086729", "33086753", "33086796",
# "33088160", "33088179", "33095078", "33117950", "33124922", "33126259", "33127395", "33140030",
# "33140049", "33145440", "33062250", "33062293", "33075883", "33079331", "33079382", "33079404",
# "33079668", "33079692", "33079706", "33079714", "33079722", "33079811", "33079820", "33079900",
# "33082030", "33082227", "33082251", "33082286", "33082316", "33082324", "33082332", "33082340",
# "33082359", "33082375", "33082430", "33084459", "33086737", "33100675", "33125341", "33125627",
# "33127514", "33128600", "33128618", "33136459", "33136483", "33136513", "33136696", "33045437",
# "33045569", "33166382", "33048347", "33048835", "33097895", "33099189", "33099286", "33110220",
# "33191280", "33062927", "33063052", "33063400", "33063877", "33064792", "33065292", "33066027",
# "33066140", "33066612", "33066620", "33067783", "33071560", "33072337", "33077088", "33077118",
# "33077126", "33077134", "33077142", "33077150", "33077169", "33077177", "33077185", "33077363",
# "33077371", "33077452", "33077487", "33077495", "33077509", "33077525", "33077568", "33077576",
# "33086427", "33087725", "33087733", "33087750", "33125805", "33126105", "33126232", "33126941",
# "33183724", "33518220", "33002126", "33002614", "33003386", "33131163", "33142319", "33518211",
# "33008272", "33011400", "33093938", "33094128", "33097003", "33100411", "33014736", "33025576",
# "33012458", "33013160", "33013837", "33013918", "33014086", "33014116", "33014310", "33013535",
# "33013551", "33013683", "33170185", "33018073", "33042543", "33018367", "33175314", "33019800",
# "33020205", "33142351", "33021708", "33021937", "33024480", "33149178", "33024880", "33025010",
# "33036632", "33036713", "33098077", "33098085", "33125449", "33029377", "33029717", "33096864",
# "33096880", "33166412", "33170169", "33097798", "33032734", "33033099", "33033110", "33033188",
# "33033196", "33156883", "33156999")

#Caso seja necessário remover ETECs incluir
# ("33049734", "33097275", "33046514", "33110476", "33095647", "33033978", "33048339", "33045445", "33096759", "33099758",
# "33028583", "33099111", "33113319", "33044880", "33097046", "33043515", "33098573", "33058199", "33058458", "33099901",
# "33058318", "33104638", "33101620", "33046662", "33008299", "33093946", "33041946", "33053340", "33043736", "33105022",
# "33032718", "33090173", "33001014", "33096830", "33090670", "33099073", "33093024", "33018804", "33027307", "33026386",
# "33028087", "33028702", "33088950", "33088896", "33096988", "33092168", "33046603", "33094063", "33003386", "33098662")


# Criar uma string com os valores a serem excluídos, separados por '|'
valores_a_excluir_str = '|'.join(valores_a_excluir)

# Converter os valores das colunas para strings e selecionar os valores que "NÃO" estão na lista de exclusão na coluna
df_exclusao = df.loc[(df['REGIONAL'].str.contains(valores_a_excluir_str)|
df['CENSO'].str.contains(valores_a_excluir_str)|
df['ESCOLARIDADE'].str.contains(valores_a_excluir_str)|
df['CURSO'].str.contains(valores_a_excluir_str)|
df['DESCRIÇÃO'].str.contains(valores_a_excluir_str))]

# Reindexar a primeira coluna
df_exclusao = df_exclusao.reset_index(drop=True)

# Visualizar o DataFrame_exclusao
display(df_exclusao)

# Salvar o DataFrame em um novo arquivo
#df_exclusao.to_excel("df_exclusao.xlsx", index=False)

,REGIONAL,MUNICÍPIO,CENSO,NOVA U.A.,ESCOLA,CURSO,ESCOLARIDADE,SÉRIE,DESCRIÇÃO,TURMA,NOME TURMA,SEMESTRE,MATRIZ,TURNO,TOTAL DE ALUNOS,TOTAL ALUNO EM PROGRESSÃO PARCIAL,SALA DE AULA,TIPO DE GESTÃO,SITUAÇÃO DA TURMA,CARÊNCIA,DURACAO,COMPARTILHADO,FORMA DE OCUPAÇÃO,SÉRIE CONCLUINTE,NECESSIDADE TOTAL,TEMPOS DE AULA
0,BAIXAD...,ARARUAMA,33026386,118023...,CIEP 2...,2.91,ENSINO...,1,NEM IT...,NEM_TS...,NEM_TS...,0,EMI_IT...,I,35,0,SL-01,ESTADUAL,COMPLETA,18,50,N,Próprio,Não,46,10
1,BAIXAD...,ARARUAMA,33026386,118023...,CIEP 2...,2.91,ENSINO...,1,NEM IT...,NEM_TS...,NEM_TS...,0,EMI_IT...,I,35,0,SL-02,ESTADUAL,COMPLETA,18,50,N,Próprio,Não,46,10
2,BAIXAD...,ARARUAMA,33026386,118023...,CIEP 2...,2.91,ENSINO...,1,NEM IT...,NEM_TS...,NEM_TS...,0,EMI_IT...,I,35,0,SL-03,ESTADUAL,COMPLETA,15,50,N,Próprio,Não,46,10
3,BAIXAD...,ARARUAMA,33026386,118023...,CIEP 2...,2.91,ENSINO...,1,NEM IT...,NEM_TS...,NEM_TS...,0,EMI_IT...,I,34,0,SL-04,ESTADUAL,COMPLETA,21,50,N,Próprio,Não,46,10
4,BAIXAD...,ARARUAMA,33026386,118023...,CIEP 2...,2.91,ENSINO...,1,NEM IT...,NEM_TS...,NEM_TS...,0,EMI_IT...,I,24,0,SL-05,ESTADUAL,COMPLETA,20,50,N,Próprio,Não,46,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20975,SUL FL...,VOLTA ...,33156999,118023...,CIEP 2...,23.22,NEM IT...,3,ENSINO...,IF_L&M...,IF_L&M...,0,NEM_IF...,N,21,0,SL-04,ESTADUAL,COMPLETA,4,45,S,Próprio,Sim,30,6
20976,SUL FL...,VOLTA ...,33156999,118023...,CIEP 2...,23.25,NEM IT...,3,ENSINO...,IF_NDS...,IF_NDS...,0,NEM_IF...,N,12,0,SL-07,ESTADUAL,COMPLETA,4,45,S,Próprio,Sim,30,6
20977,SUL FL...,VOLTA ...,33156999,118023...,CIEP 2...,2024.02,NEM IT...,2,ENSINO...,IF_LM_...,IF_LM_...,0,NEM_IF...,M,27,0,SL-05,ESTADUAL,COMPLETA,3,50,S,Próprio,Não,30,6
20978,SUL FL...,VOLTA ...,33156999,118023...,CIEP 2...,2024.05,NEM IT...,2,ENSINO...,IF_RN_...,IF_RN_...,0,NEM_IF...,M,18,0,SL-04,ESTADUAL,COMPLETA,7,50,S,Próprio,Não,30,6
20979,SUL FL...,VOLTA ...,33156999,118023...,CIEP 2...,2024.09,NEM IT...,2,ENSINO...,IT_GD_...,IT_GD_...,0,NEM_IT...,N,21,0,SL-05,ESTADUAL,COMPLETA,8,45,S,Próprio,Não,30,6

In [ ]:
# Criar uma lista com os valores a serem excluídos
valores_a_excluir = [".*CEJA.*", "^CURSOS$", "ELETIVA.*", "^EDUCAÇÃO ESPECIAL$", "^PROJETO FOCO.*", ".*SEMIPRESENCIAL.*", "^DE UNIDADES ESCOLARES PRISIONAIS E SOCIOEDUCATIVAS$", "^EJA", ".*JOVENS E ADULTOS.*", ".*ENSINO FUNDAMENTAL.*",
                    "33558221", "33034273", "33035334", "33036519", "33097224", "33096740", "33097607", "33088942",
                    "33088969", "33091323", "33062277", "33068844", "33069026", "33069034", "33069948", "33069956",
                    "33069964", "33070148", "33070156", "33070164", "33070172", "33070199", "33070326", "33071535",
                    "33071543", "33071578", "33071586", "33071616", "33072078", "33072094", "33072183", "33072205",
                    "33072280", "33072370", "33073368", "33074038", "33074046", "33074054", "33074160", "33074232",
                    "33074798", "33075174", "33075182", "33075190", "33075204", "33075220", "33075689", "33075719",
                    "33075760", "33075816", "33075832", "33075867", "33075875", "33075891", "33085463", "33085480",
                    "33085765", "33085838", "33086540", "33086567", "33086575", "33086729", "33086753", "33086796",
                    "33088160", "33088179", "33095078", "33117950", "33124922", "33126259", "33127395", "33140030",
                    "33140049", "33145440", "33062250", "33062293", "33075883", "33079331", "33079382", "33079404",
                    "33079668", "33079692", "33079706", "33079714", "33079722", "33079811", "33079820", "33079900",
                    "33082030", "33082227", "33082251", "33082286", "33082316", "33082324", "33082332", "33082340",
                    "33082359", "33082375", "33082430", "33084459", "33086737", "33100675", "33125341", "33125627",
                    "33127514", "33128600", "33128618", "33136459", "33136483", "33136513", "33136696", "33045437",
                    "33045569", "33166382", "33048347", "33048835", "33097895", "33099189", "33099286", "33110220",
                    "33191280", "33062927", "33063052", "33063400", "33063877", "33064792", "33065292", "33066027",
                    "33066140", "33066612", "33066620", "33067783", "33071560", "33072337", "33077088", "33077118",
                    "33077126", "33077134", "33077142", "33077150", "33077169", "33077177", "33077185", "33077363",
                    "33077371", "33077452", "33077487", "33077495", "33077509", "33077525", "33077568", "33077576",
                    "33086427", "33087725", "33087733", "33087750", "33125805", "33126105", "33126232", "33126941",
                    "33183724", "33518220", "33002126", "33002614", "33003386", "33131163", "33142319", "33518211",
                    "33008272", "33011400", "33093938", "33094128", "33097003", "33100411", "33014736", "33025576",
                    "33012458", "33013160", "33013837", "33013918", "33014086", "33014116", "33014310", "33013535",
                    "33013551", "33013683", "33170185", "33018073", "33042543", "33018367", "33175314", "33019800",
                    "33020205", "33142351", "33021708", "33021937", "33024480", "33149178", "33024880", "33025010",
                    "33036632", "33036713", "33098077", "33098085", "33125449", "33029377", "33029717", "33096864",
                    "33096880", "33166412", "33170169", "33097798", "33032734", "33033099", "33033110", "33033188",
                    "33033196", "33156883", "33156999",
                    "33049734", "33097275", "33046514", "33110476", "33095647", "33033978", "33048339", "33045445", "33096759", "33099758",
                    "33028583", "33099111", "33113319", "33044880", "33097046", "33043515", "33098573", "33058199", "33058458", "33099901",
                    "33058318", "33104638", "33101620", "33046662", "33008299", "33093946", "33041946", "33053340", "33043736", "33105022",
                    "33032718", "33090173", "33001014", "33096830", "33090670", "33099073", "33093024", "33018804", "33027307", "33026386",
                    "33028087", "33028702", "33088950", "33088896", "33096988", "33092168", "33046603", "33094063", "33003386", "33098662"]


#Caso seja necessário remover a PRISIONAL e manter a SOCIOEDUCAÇÃO incluir
#("33170231", "33166366", "33063044", "33063060", "33066124",
#"33079633", "33079838", "33079935", "33136467", "33136491", "33136521", "33146160",
#"33153060", "33170193", "33170215", "33172358", "33228809", "33337217", "33340200")

#Caso seja necessário remover COMPARTILHADAS incluir
# ("33558221", "33034273", "33035334", "33036519", "33097224", "33096740", "33097607", "33088942",
# "33088969", "33091323", "33062277", "33068844", "33069026", "33069034", "33069948", "33069956",
# "33069964", "33070148", "33070156", "33070164", "33070172", "33070199", "33070326", "33071535",
# "33071543", "33071578", "33071586", "33071616", "33072078", "33072094", "33072183", "33072205",
# "33072280", "33072370", "33073368", "33074038", "33074046", "33074054", "33074160", "33074232",
# "33074798", "33075174", "33075182", "33075190", "33075204", "33075220", "33075689", "33075719",
# "33075760", "33075816", "33075832", "33075867", "33075875", "33075891", "33085463", "33085480",
# "33085765", "33085838", "33086540", "33086567", "33086575", "33086729", "33086753", "33086796",
# "33088160", "33088179", "33095078", "33117950", "33124922", "33126259", "33127395", "33140030",
# "33140049", "33145440", "33062250", "33062293", "33075883", "33079331", "33079382", "33079404",
# "33079668", "33079692", "33079706", "33079714", "33079722", "33079811", "33079820", "33079900",
# "33082030", "33082227", "33082251", "33082286", "33082316", "33082324", "33082332", "33082340",
# "33082359", "33082375", "33082430", "33084459", "33086737", "33100675", "33125341", "33125627",
# "33127514", "33128600", "33128618", "33136459", "33136483", "33136513", "33136696", "33045437",
# "33045569", "33166382", "33048347", "33048835", "33097895", "33099189", "33099286", "33110220",
# "33191280", "33062927", "33063052", "33063400", "33063877", "33064792", "33065292", "33066027",
# "33066140", "33066612", "33066620", "33067783", "33071560", "33072337", "33077088", "33077118",
# "33077126", "33077134", "33077142", "33077150", "33077169", "33077177", "33077185", "33077363",
# "33077371", "33077452", "33077487", "33077495", "33077509", "33077525", "33077568", "33077576",
# "33086427", "33087725", "33087733", "33087750", "33125805", "33126105", "33126232", "33126941",
# "33183724", "33518220", "33002126", "33002614", "33003386", "33131163", "33142319", "33518211",
# "33008272", "33011400", "33093938", "33094128", "33097003", "33100411", "33014736", "33025576",
# "33012458", "33013160", "33013837", "33013918", "33014086", "33014116", "33014310", "33013535",
# "33013551", "33013683", "33170185", "33018073", "33042543", "33018367", "33175314", "33019800",
# "33020205", "33142351", "33021708", "33021937", "33024480", "33149178", "33024880", "33025010",
# "33036632", "33036713", "33098077", "33098085", "33125449", "33029377", "33029717", "33096864",
# "33096880", "33166412", "33170169", "33097798", "33032734", "33033099", "33033110", "33033188",
# "33033196", "33156883", "33156999")

#Caso seja necessário remover ETECs incluir
# ("33049734", "33097275", "33046514", "33110476", "33095647", "33033978", "33048339", "33045445", "33096759", "33099758",
# "33028583", "33099111", "33113319", "33044880", "33097046", "33043515", "33098573", "33058199", "33058458", "33099901",
# "33058318", "33104638", "33101620", "33046662", "33008299", "33093946", "33041946", "33053340", "33043736", "33105022",
# "33032718", "33090173", "33001014", "33096830", "33090670", "33099073", "33093024", "33018804", "33027307", "33026386",
# "33028087", "33028702", "33088950", "33088896", "33096988", "33092168", "33046603", "33094063", "33003386", "33098662")

# Criar uma string com os valores a serem excluídos, separados por '|'
valores_a_excluir_str = '|'.join(valores_a_excluir)

# Converter os valores das colunas para strings e selecionar os valores que "NÃO" estão na lista de exclusão na coluna
df_selecionado = df.loc[~(df['REGIONAL'].str.contains(valores_a_excluir_str)|
df['CENSO'].str.contains(valores_a_excluir_str)|
df['ESCOLARIDADE'].str.contains(valores_a_excluir_str)|
df['CURSO'].str.contains(valores_a_excluir_str)|
df['DESCRIÇÃO'].str.contains(valores_a_excluir_str))]

# Reindexar a primeira coluna
df_selecionado = df_selecionado.reset_index(drop=True)

# Visualizar o DataFrame selecionado
display(df_selecionado)

# Salvar o DataFrame em um novo arquivo
#df_selecionado.to_excel("df_selecionado.xlsx", index=False)

,REGIONAL,MUNICÍPIO,CENSO,NOVA U.A.,ESCOLA,CURSO,ESCOLARIDADE,SÉRIE,DESCRIÇÃO,TURMA,NOME TURMA,SEMESTRE,MATRIZ,TURNO,TOTAL DE ALUNOS,TOTAL ALUNO EM PROGRESSÃO PARCIAL,SALA DE AULA,TIPO DE GESTÃO,SITUAÇÃO DA TURMA,CARÊNCIA,DURACAO,COMPARTILHADO,FORMA DE OCUPAÇÃO,SÉRIE CONCLUINTE,NECESSIDADE TOTAL,TEMPOS DE AULA
0,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,2.61,NOVO E...,1,ENSINO...,1001,1001-1...,0,NOV_EN...,M,39,0,SL-01,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,30,6
1,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,2.61,NOVO E...,1,ENSINO...,1002,1002-1...,0,NOV_EN...,M,40,0,SL-09,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,30,6
2,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,2.61,NOVO E...,1,ENSINO...,1003,1003-1...,0,NOV_EN...,N,39,0,SL-01,ESTADUAL,COMPLETA,4,45,N,Próprio,Não,30,6
3,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,23.24,NEM IT...,3,ENSINO...,IF_PSC...,IF_PSC...,0,NEM_IF...,M,35,0,SL-05,ESTADUAL,COMPLETA,10,50,N,Próprio,Sim,30,6
4,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,23.38,NEM IT...,3,ENSINO...,IF_GDI...,IF_GDI...,0,NEM_IF...,N,28,0,SL-09,ESTADUAL,COMPLETA,2,45,N,Próprio,Sim,30,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12502,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,2.84,ENSINO...,1,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,35,0,SL-01,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,46,10
12503,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,2.84,ENSINO...,1,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,33,0,SL-02,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,46,10
12504,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,2.84,ENSINO...,1,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,35,0,SL-03,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,46,10
12505,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,2.84,ENSINO...,2,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,23,0,SL-05,ESTADUAL,COMPLETA,0,50,N,Próprio,Não,46,10
12506,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,2.84,ENSINO...,3,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,22,0,SL-06,ESTADUAL,COMPLETA,4,50,N,Próprio,Sim,46,10

In [ ]:
df_selecionado.describe()

,NOVA U.A.,SÉRIE,SEMESTRE,TOTAL DE ALUNOS,TOTAL ALUNO EM PROGRESSÃO PARCIAL,CARÊNCIA,DURACAO,NECESSIDADE TOTAL,TEMPOS DE AULA
count,1.2507...,12507....,12507....,12507....,12507....,12507....,12507....,12507....,12507....
mean,1.1802...,1.944911,0.006476,28.970017,0.460302,4.612377,49.262013,32.051491,6.654513
std,3.7556...,0.820390,0.080218,11.138515,2.626140,4.650927,2.379990,5.440039,1.666745
min,1.1802...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17.000000,6.000000
25%,1.1802...,1.000000,0.000000,21.000000,0.000000,1.000000,50.000000,30.000000,6.000000
50%,1.1802...,2.000000,0.000000,31.000000,0.000000,4.000000,50.000000,30.000000,6.000000
75%,1.1802...,3.000000,0.000000,38.000000,0.000000,7.000000,50.000000,30.000000,6.000000
max,1.1802...,7.000000,1.000000,50.000000,84.000000,48.000000,50.000000,56.000000,12.000000

In [ ]:
#quantas linhas
df_selecionado.shape[0]

12507

In [ ]:
#quantas colunas
df_selecionado.shape[1]

26

In [ ]:
print('Temos %0.f linhas e %0.f colunas'%(df_selecionado.shape[0], df_selecionado.shape[1]))

Temos 12507 linhas e 26 colunas

In [ ]:
df_selecionado.columns

Index(['REGIONAL', 'MUNICÍPIO', 'CENSO', 'NOVA U.A.', 'ESCOLA', 'CURSO',
       'ESCOLARIDADE', 'SÉRIE', 'DESCRIÇÃO', 'TURMA', 'NOME TURMA ',
       'SEMESTRE', 'MATRIZ', 'TURNO', 'TOTAL DE ALUNOS',
       'TOTAL ALUNO EM PROGRESSÃO PARCIAL', 'SALA DE AULA', 'TIPO DE GESTÃO',
       'SITUAÇÃO DA TURMA', 'CARÊNCIA', 'DURACAO', 'COMPARTILHADO',
       'FORMA DE OCUPAÇÃO', 'SÉRIE CONCLUINTE', 'NECESSIDADE TOTAL',
       'TEMPOS DE AULA'],
      dtype='object')

In [ ]:
#seleciona valores únicos de uma coluna

df_selecionado['REGIONAL'].unique()

array(['BAIXADAS LITORANEAS', 'CENTRO SUL', 'METROPOLITANA I',
       'METROPOLITANA II ', 'METROPOLITANA III', 'METROPOLITANA IV',
       'METROPOLITANA V', 'METROPOLITANA VI', 'METROPOLITANA VII',
       'NOROESTE FLUMINENSE', 'NORTE FLUMINENSE', 'SERRANA I',
       'SERRANA II', 'SUL FLUMINENSE'], dtype=object)

In [ ]:
#redefine tamanho da coluna

pd.set_option('max_colwidth', 10)

In [ ]:
pd.set_option('display.max_rows', 99)

In [ ]:
pd.set_option('display.max_columns', 99)

In [ ]:
display(df_selecionado)

,REGIONAL,MUNICÍPIO,CENSO,NOVA U.A.,ESCOLA,CURSO,ESCOLARIDADE,SÉRIE,DESCRIÇÃO,TURMA,NOME TURMA,SEMESTRE,MATRIZ,TURNO,TOTAL DE ALUNOS,TOTAL ALUNO EM PROGRESSÃO PARCIAL,SALA DE AULA,TIPO DE GESTÃO,SITUAÇÃO DA TURMA,CARÊNCIA,DURACAO,COMPARTILHADO,FORMA DE OCUPAÇÃO,SÉRIE CONCLUINTE,NECESSIDADE TOTAL,TEMPOS DE AULA
0,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,2.61,NOVO E...,1,ENSINO...,1001,1001-1...,0,NOV_EN...,M,39,0,SL-01,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,30,6
1,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,2.61,NOVO E...,1,ENSINO...,1002,1002-1...,0,NOV_EN...,M,40,0,SL-09,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,30,6
2,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,2.61,NOVO E...,1,ENSINO...,1003,1003-1...,0,NOV_EN...,N,39,0,SL-01,ESTADUAL,COMPLETA,4,45,N,Próprio,Não,30,6
3,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,23.24,NEM IT...,3,ENSINO...,IF_PSC...,IF_PSC...,0,NEM_IF...,M,35,0,SL-05,ESTADUAL,COMPLETA,10,50,N,Próprio,Sim,30,6
4,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,23.38,NEM IT...,3,ENSINO...,IF_GDI...,IF_GDI...,0,NEM_IF...,N,28,0,SL-09,ESTADUAL,COMPLETA,2,45,N,Próprio,Sim,30,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12502,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,2.84,ENSINO...,1,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,35,0,SL-01,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,46,10
12503,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,2.84,ENSINO...,1,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,33,0,SL-02,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,46,10
12504,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,2.84,ENSINO...,1,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,35,0,SL-03,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,46,10
12505,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,2.84,ENSINO...,2,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,23,0,SL-05,ESTADUAL,COMPLETA,0,50,N,Próprio,Não,46,10
12506,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,2.84,ENSINO...,3,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,22,0,SL-06,ESTADUAL,COMPLETA,4,50,N,Próprio,Sim,46,10

In [ ]:
df_selecionado['TOTAL DE ALUNOS'].describe(percentiles=[0.1, 0.2, 0.3, 0.4, 0.5, 0.99])

count    12507....
mean     28.970017
std      11.138515
min       0.000000
10%      12.000000
20%      19.000000
30%      24.000000
40%      28.000000
50%      31.000000
99%      45.000000
max      50.000000
Name: TOTAL DE ALUNOS, dtype: float64

In [ ]:
df_selecionado.agg({'TOTAL DE ALUNOS':['sum', 'min', 'max', 'skew', 'median'], 'TOTAL ALUNO EM PROGRESSÃO PARCIAL':['sum', 'min', 'max', 'skew', 'median']})

        TOTAL DE ALUNOS  TOTAL ALUNO EM PROGRESSÃO PARCIAL
sum     362328...        5757.0...
min      0.000000         0.000000
max     50.000000        84.000000
skew    -0.593114        11.513044
median  31.000000         0.000000

In [ ]:
df_selecionado.groupby('REGIONAL')['TOTAL DE ALUNOS', 'TOTAL ALUNO EM PROGRESSÃO PARCIAL'].sum().sort_values(by='TOTAL DE ALUNOS', ascending=False)

<ipython-input-47-8baba0c272cf>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_selecionado.groupby('REGIONAL')['TOTAL DE ALUNOS', 'TOTAL ALUNO EM PROGRESSÃO PARCIAL'].sum().sort_values(by='TOTAL DE ALUNOS', ascending=False)

            TOTAL DE ALUNOS  TOTAL ALUNO EM PROGRESSÃO PARCIAL
REGIONAL
METROPO...      53950              383
METROPO...      34473             1252
BAIXADA...      33419              390
METROPO...      33282             1216
METROPO...      31541              187
METROPO...      28625               36
NORTE F...      25348              150
SERRANA I       24896              326
METROPO...      23342              327
METROPO...      23320              152
SUL FLU...      22299              171
SERRANA II      11088              118
CENTRO SUL       9497              933
NOROEST...       7248              116

In [ ]:
import numpy as np
pd.pivot_table(df_selecionado, index='REGIONAL', aggfunc=np.sum)

<ipython-input-48-5ba427623f1b>:2: FutureWarning: The operation <function sum at 0x790ece1120e0> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  pd.pivot_table(df_selecionado, index='REGIONAL', aggfunc=np.sum)

,CARÊNCIA,DURACAO,NECESSIDADE TOTAL,NOVA U.A.,SEMESTRE,SÉRIE,TEMPOS DE AULA,TOTAL ALUNO EM PROGRESSÃO PARCIAL,TOTAL DE ALUNOS
REGIONAL,,,,,,,,,
BAIXADAS LITORANEAS,5305,57150,37764,137024...,3,2250,7850,390,33419
CENTRO SUL,1517,20010,13246,477993...,0,800,2784,933,9497
METROPOLITANA I,5063,51140,33632,122153...,0,2023,7004,187,31541
METROPOLITANA II,3813,43140,27658,103034...,0,1706,5666,152,23320
METROPOLITANA III,4175,52765,34126,126874...,0,2046,7020,1216,33282
METROPOLITANA IV,7801,81750,51902,195210...,6,3176,10630,383,53950
METROPOLITANA V,3344,39170,25412,938283...,0,1562,5234,327,23342
METROPOLITANA VI,4068,43825,28338,105276...,8,1723,5846,36,28625
METROPOLITANA VII,5491,57300,36825,137260...,39,2288,7628,1252,34473
NOROESTE FLUMINENSE,1574,18390,13000,442586...,0,744,2834,116,7248
NORTE FLUMINENSE,6010,47335,30490,113538...,6,1881,6322,150,25348
SERRANA I,3633,42100,27403,101145...,11,1653,5730,326,24896
SERRANA II,2535,22720,15428,547627...,0,908,3288,118,11088
SUL FLUMINENSE,3358,39325,25644,939463...,8,1565,5392,171,22299

In [ ]:
pd.pivot_table(df_selecionado, index=['REGIONAL'], values=['TOTAL DE ALUNOS', 'TOTAL ALUNO EM PROGRESSÃO PARCIAL'], aggfunc=np.sum).sort_values(by='TOTAL DE ALUNOS', ascending=False)

            TOTAL ALUNO EM PROGRESSÃO PARCIAL  TOTAL DE ALUNOS
REGIONAL
METROPO...        383                              53950
METROPO...       1252                              34473
BAIXADA...        390                              33419
METROPO...       1216                              33282
METROPO...        187                              31541
METROPO...         36                              28625
NORTE F...        150                              25348
SERRANA I         326                              24896
METROPO...        327                              23342
METROPO...        152                              23320
SUL FLU...        171                              22299
SERRANA II        118                              11088
CENTRO SUL        933                               9497
NOROEST...        116                               7248

In [ ]:
pd.pivot_table(df_selecionado, index=['REGIONAL', 'MUNICÍPIO'], columns=['SÉRIE'], values=['TOTAL DE ALUNOS', 'TOTAL ALUNO EM PROGRESSÃO PARCIAL'], aggfunc=np.sum)

                      TOTAL ALUNO EM PROGRESSÃO PARCIAL                    \
SÉRIE                                                 1      2     3    4
REGIONAL   MUNICÍPIO
BAIXADA... ARARUAMA          0.0                           1.0   0.0  NaN
           ARMAÇÃO...        0.0                           0.0   0.0  NaN
           ARRAIAL...        0.0                           0.0   0.0  NaN
           CABO FRIO        50.0                          30.0   0.0  NaN
           IGUABA ...        0.0                           0.0   0.0  NaN
           MARICÁ           64.0                          24.0   0.0  NaN
           NITERÓI         147.0                          62.0   0.0  NaN
           RIO BONITO        0.0                           0.0   0.0  NaN
           SAQUAREMA         1.0                          11.0   0.0  NaN
           SÃO PED...        0.0                           0.0   0.0  NaN
CENTRO SUL BARRA D...      135.0                          59.0   0.0  NaN
           ENGENHE...       20.0                           2.0   1.0  NaN
           MENDES           17.0                           3.0   1.0  NaN
           MIGUEL ...       85.0                          26.0   0.0  NaN
           PARACAMBI        41.0                          38.0   0.0  NaN
           PARAÍBA...       75.0                          49.0   1.0  NaN
           PATY DO...       42.0                          40.0   0.0  NaN
           RIO DAS...       14.0                           3.0   2.0  NaN
           VALENÇA          79.0                          49.0   3.0  NaN
           VASSOURAS        77.0                          71.0   0.0  NaN
METROPO... JAPERI            0.0                           0.0   0.0  NaN
           NOVA IG...      114.0                          61.0  12.0  NaN
           QUEIMADOS         0.0                           0.0   0.0  NaN
METROPO... ITABORAÍ          2.0                           1.0   0.0  NaN
           SÃO GON...       56.0                          93.0   0.0  NaN
           TANGUÁ            0.0                           0.0   0.0  NaN
METROPO... RIO DE ...      686.0                         517.0  13.0  NaN
METROPO... ITAGUAÍ          50.0                          38.0   1.0  NaN
           RIO DE ...      210.0                          83.0   0.0  NaN
           SEROPÉDICA        0.0                           1.0   0.0  NaN
METROPO... DUQUE D...      222.0                         105.0   0.0  NaN
METROPO... RIO DE ...       18.0                          18.0   0.0  0.0
METROPO... BELFORD...      212.0                         114.0   1.0  NaN
           MESQUITA        110.0                          63.0   0.0  NaN
           NILÓPOLIS       155.0                          99.0   2.0  NaN
           SÃO JOÃ...      283.0                         210.0   3.0  0.0
NOROEST... APERIBÉ           0.0                           0.0   0.0  NaN
           BOM JES...        5.0                           0.0   0.0  NaN
           CAMBUCÍ           0.0                           0.0   0.0  NaN
           ITALVA            0.0                           0.0   0.0  NaN
           ITAOCARA         10.0                           4.0   0.0  NaN
           ITAPERUNA         3.0                           5.0   0.0  NaN
           LAJE DO...        0.0                           0.0   0.0  NaN
           MIRACEMA         10.0                          16.0   0.0  NaN
           NATIVIDADE        0.0                           0.0   0.0  NaN
           PORCIÚN...        0.0                           0.0   0.0  NaN
           SANTO A...        0.0                           0.0   0.0  NaN
           SÃO JOS...        0.0                           0.0   0.0  NaN
           VARRE-SAI        37.0                          26.0   0.0  NaN
NORTE F... CAMPOS ...       42.0                          37.0   0.0  NaN
           CARAPEBUS         0.0                           0.0   0.0  NaN
           CARDOSO...        0.0                           0.0   0.0  NaN
           CONCEIÇ...        0.0                           0.0   0.0  NaN
           MACAÉ            32.0                           9.0   0.0  NaN
           QUISSAMÃ          0.0                           0.0   0.0  NaN
           RIO DAS...        0.0                           0.0   0.0  NaN
           SÃO FID...       19.0                          11.0   0.0  0.0
           SÃO FRA...        0.0                           0.0   0.0  NaN
           SÃO JOÃ...        0.0                           0.0   0.0  NaN
SERRANA I  AREAL             0.0                           0.0   0.0  NaN
           COMENDA...        0.0                           0.0   0.0  NaN
           GUAPIMIRIM       25.0                           7.0   1.0  NaN
           MAGÉ             12.0                           0.0   0.0  NaN
           PETRÓPOLIS       71.0                          47.0   2.0  NaN
           SAPUCAIA          0.0                           0.0   0.0  NaN
           SÃO JOS...        0.0                           0.0   0.0  NaN
           TERESÓP...       42.0                          45.0   0.0  NaN
           TRÊS RIOS        59.0                          15.0   0.0  NaN
SERRANA II BOM JARDIM        3.0                           5.0   0.0  NaN
           CACHOEI...        0.0                           0.0   0.0  NaN
           CANTAGALO         0.0                           0.0   0.0  NaN
           CARMO             0.0                           0.0   0.0  NaN
           CASIMIR...        0.0                           1.0   0.0  NaN
           CORDEIRO          0.0                           0.0   0.0  NaN
           DUAS BA...       12.0                           3.0   0.0  NaN
           MACUCO            0.0                           0.0   0.0  NaN
           NOVA FR...       47.0                          34.0   0.0  NaN
           SANTA M...       10.0                           2.0   0.0  NaN
           SILVA J...        0.0                           0.0   0.0  NaN
           SUMIDOURO         0.0                           0.0   0.0  NaN
           SÃO SEB...        0.0                           0.0   0.0  NaN
           TRAJANO...        0.0                           1.0   0.0  NaN
SUL FLU... ANGRA D...       38.0                          59.0   0.0  NaN
           BARRA M...        5.0                          10.0   0.0  0.0
           ITATIAIA          0.0                           0.0   0.0  NaN
           MANGARA...        0.0                           1.0   0.0  NaN
           PARATY            0.0                           0.0   0.0  NaN
           PINHEIRAL         0.0                           0.0   0.0  NaN
           PIRAÍ             6.0                           4.0   0.0  NaN
           PORTO REAL        0.0                           0.0   0.0  NaN
           QUATIS            0.0                           0.0   0.0  NaN
           RESENDE           0.0                           0.0   0.0  NaN
           RIO CLARO        15.0                          12.0   0.0  NaN
           VOLTA R...       12.0                           9.0   0.0  NaN

                           TOTAL DE ALUNOS
SÉRIE                    7               1        2        3     4    7
REGIONAL   MUNICÍPIO
BAIXADA... ARARUAMA    NaN     1269.0        1103.0    961.0   NaN  NaN
           ARMAÇÃO...  NaN      415.0         231.0    187.0   NaN  NaN
           ARRAIAL...  NaN      329.0         270.0    215.0   NaN  NaN
           CABO FRIO   NaN     1714.0        1238.0   1071.0   NaN  NaN
           IGUABA ...  NaN      280.0         327.0    267.0   NaN  NaN
           MARICÁ      NaN     2827.0        2142.0   1746.0   NaN  NaN
           NITERÓI     NaN     4077.0        3039.0   2686.0   NaN  NaN
           RIO BONITO  NaN      640.0         530.0    524.0   NaN  NaN
           SAQUAREMA   NaN     1070.0         861.0    762.0   NaN  NaN
           SÃO PED...  NaN     1014.0         874.0    750.0   NaN  NaN
CENTRO SUL BARRA D...  NaN      734.0         529.0    476.0   NaN  NaN
           ENGENHE...  NaN      156.0         150.0    174.0   NaN  NaN
           MENDES      NaN      109.0         104.0     79.0   NaN  NaN
           MIGUEL ...  NaN      305.0         251.0    212.0   NaN  NaN
           PARACAMBI   NaN      441.0         311.0    306.0   NaN  NaN
           PARAÍBA...  NaN      499.0         430.0    380.0   NaN  NaN
           PATY DO...  NaN      316.0         287.0    263.0   NaN  NaN
           RIO DAS...  NaN       84.0          64.0     43.0   NaN  NaN
           VALENÇA     NaN      663.0         536.0    554.0   NaN  NaN
           VASSOURAS   NaN      411.0         341.0    289.0   NaN  NaN
METROPO... JAPERI      NaN     1166.0        1008.0    837.0   NaN  NaN
           NOVA IG...  NaN     8933.0        7737.0   6817.0   NaN  NaN
           QUEIMADOS   NaN     1857.0        1659.0   1527.0   NaN  NaN
METROPO... ITABORAÍ    NaN     2021.0        1761.0   1503.0   NaN  NaN
           SÃO GON...  NaN     6926.0        5454.0   4775.0   NaN  NaN
           TANGUÁ      NaN      343.0         263.0    274.0   NaN  NaN
METROPO... RIO DE ...  NaN    14441.0        9895.0   8946.0   NaN  NaN
METROPO... ITAGUAÍ     NaN     1348.0        1071.0    961.0   NaN  NaN
           RIO DE ...  NaN    20665.0       14966.0  13699.0   NaN  NaN
           SEROPÉDICA  NaN      498.0         391.0    351.0   NaN  NaN
METROPO... DUQUE D...  NaN     9136.0        7554.0   6652.0   NaN  NaN
METROPO... RIO DE ...  NaN    12168.0        8702.0   7730.0  25.0  NaN
METROPO... BELFORD...  NaN     4214.0        3647.0   3138.0   NaN  NaN
           MESQUITA    NaN     1530.0        1351.0   1111.0   NaN  NaN
           NILÓPOLIS   NaN     2412.0        1955.0   1839.0   NaN  NaN
           SÃO JOÃ...  NaN     5115.0        4316.0   3844.0   1.0  NaN
NOROEST... APERIBÉ     NaN       38.0          34.0     43.0   NaN  NaN
           BOM JES...  NaN      347.0         268.0    236.0   NaN  NaN
           CAMBUCÍ     NaN       97.0          77.0    100.0   NaN  NaN
           ITALVA      NaN       61.0          47.0     73.0   NaN  NaN
           ITAOCARA    NaN      221.0         231.0    217.0   NaN  NaN
           ITAPERUNA   NaN      795.0         776.0    727.0   NaN  NaN
           LAJE DO...  NaN       63.0          75.0     63.0   NaN  NaN
           MIRACEMA    NaN      278.0         275.0    233.0   NaN  NaN
           NATIVIDADE  NaN       72.0          68.0     89.0   NaN  NaN
           PORCIÚN...  NaN      163.0         150.0    137.0   NaN  NaN
           SANTO A...  NaN      246.0         209.0    230.0   NaN  NaN
           SÃO JOS...  NaN       51.0          52.0     47.0   NaN  NaN
           VARRE-SAI   NaN      142.0         118.0     99.0   NaN  NaN
NORTE F... CAMPOS ...  NaN     4437.0        3598.0   3157.0   NaN  NaN
           CARAPEBUS   NaN      196.0         109.0     95.0   NaN  NaN
           CARDOSO...  NaN      129.0         111.0    113.0   NaN  NaN
           CONCEIÇ...  NaN      222.0         174.0    183.0   NaN  NaN
           MACAÉ       NaN     2503.0        1987.0   1715.0   NaN  NaN
           QUISSAMÃ    NaN      254.0         174.0    135.0   NaN  NaN
           RIO DAS...  NaN     1558.0        1202.0   1078.0   NaN  NaN
           SÃO FID...  NaN      262.0         239.0    231.0  24.0  NaN
           SÃO FRA...  NaN      322.0         281.0    241.0   NaN  NaN
           SÃO JOÃ...  NaN      236.0         216.0    166.0   NaN  NaN
SERRANA I  AREAL       NaN      162.0         144.0    118.0   NaN  NaN
           COMENDA...  NaN       94.0          93.0     97.0   NaN  NaN
           GUAPIMIRIM  NaN      583.0         451.0    431.0   NaN  NaN
           MAGÉ        NaN     3374.0        2881.0   2519.0   NaN  NaN
           PETRÓPOLIS  NaN     2607.0        1916.0   1703.0   NaN  NaN
           SAPUCAIA    NaN      255.0         243.0    205.0   NaN  NaN
           SÃO JOS...  NaN      232.0         213.0    165.0   NaN  NaN
           TERESÓP...  NaN     1771.0        1401.0   1235.0   NaN  NaN
           TRÊS RIOS   NaN      856.0         632.0    515.0   NaN  NaN
SERRANA II BOM JARDIM  NaN      324.0         185.0    188.0   NaN  NaN
           CACHOEI...  NaN      495.0         419.0    438.0   NaN  NaN
           CANTAGALO   NaN      165.0         134.0    137.0   NaN  NaN
           CARMO       NaN      196.0         169.0    126.0   NaN  NaN
           CASIMIR...  NaN      784.0         634.0    527.0   NaN  NaN
           CORDEIRO    NaN      205.0         182.0    177.0   NaN  NaN
           DUAS BA...  NaN       67.0          75.0     65.0   NaN  NaN
           MACUCO      NaN      124.0          98.0     94.0   NaN  NaN
           NOVA FR...  NaN     1460.0        1067.0    924.0   NaN  NaN
           SANTA M...  NaN       78.0          77.0     68.0   NaN  NaN
           SILVA J...  NaN      292.0         228.0    194.0   NaN  NaN
           SUMIDOURO   NaN      107.0          42.0     50.0   NaN  NaN
           SÃO SEB...  NaN       50.0          42.0     45.0   NaN  NaN
           TRAJANO...  NaN      121.0         120.0    115.0   NaN  NaN
SUL FLU... ANGRA D...  0.0     1410.0        1121.0    895.0   NaN  0.0
           BARRA M...  NaN     1393.0        1203.0   1084.0  10.0  NaN
           ITATIAIA    NaN      217.0         193.0    165.0   NaN  NaN
           MANGARA...  NaN      419.0         287.0    277.0   NaN  NaN
           PARATY      NaN      521.0         466.0    354.0   NaN  NaN
           PINHEIRAL   NaN      247.0         224.0    170.0   NaN  NaN
           PIRAÍ       NaN      328.0         275.0    218.0   NaN  NaN
           PORTO REAL  NaN      177.0         115.0     97.0   NaN  NaN
           QUATIS      NaN      183.0          95.0    117.0   NaN  NaN
           RESENDE     NaN     1436.0        1236.0   1057.0   NaN  NaN
           RIO CLARO   NaN      245.0         260.0    167.0   NaN  NaN
           VOLTA R...  NaN     2223.0        1731.0   1683.0   NaN  NaN

In [ ]:
df_selecionado.REGIONAL.value_counts(normalize=True)

METROPOLITANA IV       0.132246
METROPOLITANA VII      0.092988
BAIXADAS LITORANEAS    0.092828
METROPOLITANA III      0.085952
METROPOLITANA I        0.082754
NORTE FLUMINENSE       0.076917
METROPOLITANA VI       0.071320
METROPOLITANA II       0.069801
SERRANA I              0.068522
SUL FLUMINENSE         0.063644
METROPOLITANA V        0.063564
SERRANA II             0.037099
CENTRO SUL             0.032382
NOROESTE FLUMINENSE    0.029983
Name: REGIONAL, dtype: float64

In [ ]:
df_selecionado.groupby('REGIONAL')['MUNICÍPIO'].value_counts()

REGIONAL             MUNICÍPIO
BAIXADAS LITORANEAS  NITERÓI                           386
                     MARICÁ                            225
                     CABO FRIO                         141
                     ARARUAMA                           99
                     SÃO PEDRO DA ALDEIA                82
                     SAQUAREMA                          78
                     RIO BONITO                         74
                     ARRAIAL DO CABO                    27
                     ARMAÇÃO DOS BÚZIOS                 26
                     IGUABA GRANDE                      23
CENTRO SUL           VALENÇA                            82
                     BARRA DO PIRAÍ                     70
                     PARAÍBA DO SUL                     56
                     VASSOURAS                          45
                     PARACAMBI                          41
                     PATY DO ALFERES                    35
                     MIGUEL PEREIRA                     30
                     ENGENHEIRO PAULO DE FRONTIN        21
                     MENDES                             15
                     RIO DAS FLORES                     10
METROPOLITANA I      NOVA IGUAÇU                       787
                     QUEIMADOS                         147
                     JAPERI                            101
METROPOLITANA II     SÃO GONÇALO                       657
                     ITABORAÍ                          186
                     TANGUÁ                             30
METROPOLITANA III    RIO DE JANEIRO                   1075
METROPOLITANA IV     RIO DE JANEIRO                   1487
                     ITAGUAÍ                           122
                     SEROPÉDICA                         45
METROPOLITANA V      DUQUE DE CAXIAS                   795
METROPOLITANA VI     RIO DE JANEIRO                    892
METROPOLITANA VII    SÃO JOÃO DE MERITI                461
                     BELFORD ROXO                      358
                     NILÓPOLIS                         205
                     MESQUITA                          139
NOROESTE FLUMINENSE  ITAPERUNA                         102
                     BOM JESUS DO ITABAPOANA            45
                     ITAOCARA                           37
                     MIRACEMA                           35
                     SANTO ANTÔNIO DE PÁDUA             34
                     CAMBUCÍ                            30
                     PORCIÚNCULA                        27
                     VARRE-SAI                          15
                     NATIVIDADE                         12
                     APERIBÉ                            10
                     LAJE DO MURIAÉ                     10
                     ITALVA                              9
                     SÃO JOSÉ DE UBÁ                     9
NORTE FLUMINENSE     CAMPOS DOS GOYTACAZES             477
                     MACAÉ                             209
                     RIO DAS OSTRAS                    101
                     SÃO FRANCISCO DE ITABAPOANA        37
                     SÃO FIDÉLIS                        36
                     SÃO JOÃO DA BARRA                  31
                     CONCEIÇÃO DE MACABU                22
                     QUISSAMÃ                           20
                     CARDOSO MOREIRA                    15
                     CARAPEBUS                          14
SERRANA I            MAGÉ                              294
                     PETRÓPOLIS                        209
                     TERESÓPOLIS                       144
                     TRÊS RIOS                          78
                     GUAPIMIRIM                         50
                     SAPUCAIA                           32
                     SÃO JOSÉ DO VALE DO RIO PRETO      22
                     AREAL                              17
                     COMENDADOR LEVY GASPARIAN          11
SERRANA II           NOVA FRIBURGO                     145
                     CASIMIRO DE ABREU                  67
                     CACHOEIRAS DE MACACU               55
                     BOM JARDIM                         38
                     SILVA JARDIM                       26
                     CARMO                              24
                     CANTAGALO                          23
                     CORDEIRO                           23
                     MACUCO                             17
                     TRAJANO DE MORAES                  15
                     DUAS BARRAS                         9
                     SANTA MARIA MADALENA                9
                     SUMIDOURO                           7
                     SÃO SEBASTIÃO DO ALTO               6
SUL FLUMINENSE       VOLTA REDONDA                     199
                     BARRA MANSA                       135
                     RESENDE                           125
                     ANGRA DOS REIS                    119
                     PARATY                             50
                     MANGARATIBA                        36
                     PIRAÍ                              34
                     RIO CLARO                          30
                     PINHEIRAL                          20
                     ITATIAIA                           17
                     QUATIS                             16
                     PORTO REAL                         15
Name: MUNICÍPIO, dtype: int64

In [ ]:
df.isna()

,REGIONAL,MUNICÍPIO,CENSO,NOVA U.A.,ESCOLA,CURSO,ESCOLARIDADE,SÉRIE,DESCRIÇÃO,TURMA,NOME TURMA,SEMESTRE,MATRIZ,TURNO,TOTAL DE ALUNOS,TOTAL ALUNO EM PROGRESSÃO PARCIAL,SALA DE AULA,TIPO DE GESTÃO,SITUAÇÃO DA TURMA,CARÊNCIA,DURACAO,COMPARTILHADO,FORMA DE OCUPAÇÃO,SÉRIE CONCLUINTE,NECESSIDADE TOTAL,TEMPOS DE AULA
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33482,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
33483,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
33484,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
33485,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
33486,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isna().sum()

REGIONAL                             0
MUNICÍPIO                            0
CENSO                                0
NOVA U.A.                            0
ESCOLA                               0
CURSO                                0
ESCOLARIDADE                         0
SÉRIE                                0
DESCRIÇÃO                            0
TURMA                                0
NOME TURMA                           0
SEMESTRE                             0
MATRIZ                               0
TURNO                                0
TOTAL DE ALUNOS                      0
TOTAL ALUNO EM PROGRESSÃO PARCIAL    0
SALA DE AULA                         0
TIPO DE GESTÃO                       0
SITUAÇÃO DA TURMA                    0
CARÊNCIA                             0
DURACAO                              0
COMPARTILHADO                        0
FORMA DE OCUPAÇÃO                    0
SÉRIE CONCLUINTE                     0
NECESSIDADE TOTAL                    0
TEMPOS DE AULA                       0
dtype: int64

In [ ]:
# Excluir linhas que contém as expressões procuradas, pois o símbolo "~", está antes demarcado antes do dataframe
d = df_selecionado[~df_selecionado['REGIONAL'].str.contains('.*PRISIONAIS*.|.*BAIXADAS*.', regex=True)]
display(d['REGIONAL'].unique())

array(['CENTRO SUL', 'METROPOLITANA I', 'METROPOLITANA II ',
       'METROPOLITANA III', 'METROPOLITANA IV', 'METROPOLITANA V',
       'METROPOLITANA VI', 'METROPOLITANA VII', 'NOROESTE FLUMINENSE',
       'NORTE FLUMINENSE', 'SERRANA I', 'SERRANA II', 'SUL FLUMINENSE'],
      dtype=object)

In [ ]:
df_selecionado['CURSO'] = df_selecionado['CURSO'].apply(lambda x: "{:0>7}".format(x))
display(df_selecionado)

,REGIONAL,MUNICÍPIO,CENSO,NOVA U.A.,ESCOLA,CURSO,ESCOLARIDADE,SÉRIE,DESCRIÇÃO,TURMA,NOME TURMA,SEMESTRE,MATRIZ,TURNO,TOTAL DE ALUNOS,TOTAL ALUNO EM PROGRESSÃO PARCIAL,SALA DE AULA,TIPO DE GESTÃO,SITUAÇÃO DA TURMA,CARÊNCIA,DURACAO,COMPARTILHADO,FORMA DE OCUPAÇÃO,SÉRIE CONCLUINTE,NECESSIDADE TOTAL,TEMPOS DE AULA
0,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,0002.61,NOVO E...,1,ENSINO...,1001,1001-1...,0,NOV_EN...,M,39,0,SL-01,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,30,6
1,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,0002.61,NOVO E...,1,ENSINO...,1002,1002-1...,0,NOV_EN...,M,40,0,SL-09,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,30,6
2,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,0002.61,NOVO E...,1,ENSINO...,1003,1003-1...,0,NOV_EN...,N,39,0,SL-01,ESTADUAL,COMPLETA,4,45,N,Próprio,Não,30,6
3,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,0023.24,NEM IT...,3,ENSINO...,IF_PSC...,IF_PSC...,0,NEM_IF...,M,35,0,SL-05,ESTADUAL,COMPLETA,10,50,N,Próprio,Sim,30,6
4,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,0023.38,NEM IT...,3,ENSINO...,IF_GDI...,IF_GDI...,0,NEM_IF...,N,28,0,SL-09,ESTADUAL,COMPLETA,2,45,N,Próprio,Sim,30,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12502,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,0002.84,ENSINO...,1,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,35,0,SL-01,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,46,10
12503,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,0002.84,ENSINO...,1,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,33,0,SL-02,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,46,10
12504,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,0002.84,ENSINO...,1,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,35,0,SL-03,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,46,10
12505,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,0002.84,ENSINO...,2,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,23,0,SL-05,ESTADUAL,COMPLETA,0,50,N,Próprio,Não,46,10
12506,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,0002.84,ENSINO...,3,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,22,0,SL-06,ESTADUAL,COMPLETA,4,50,N,Próprio,Sim,46,10

In [ ]:
#Total para colunas numéricas, instalando o numpy
df_selecionado.loc['TOTAL'] = 0
df_selecionado.loc['TOTAL'] = df_selecionado.select_dtypes(include=[np.number]).sum()
display(df_selecionado)

,REGIONAL,MUNICÍPIO,CENSO,NOVA U.A.,ESCOLA,CURSO,ESCOLARIDADE,SÉRIE,DESCRIÇÃO,TURMA,NOME TURMA,SEMESTRE,MATRIZ,TURNO,TOTAL DE ALUNOS,TOTAL ALUNO EM PROGRESSÃO PARCIAL,SALA DE AULA,TIPO DE GESTÃO,SITUAÇÃO DA TURMA,CARÊNCIA,DURACAO,COMPARTILHADO,FORMA DE OCUPAÇÃO,SÉRIE CONCLUINTE,NECESSIDADE TOTAL,TEMPOS DE AULA
0,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,0002.61,NOVO E...,1,ENSINO...,1001,1001-1...,0,NOV_EN...,M,39,0,SL-01,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,30,6
1,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,0002.61,NOVO E...,1,ENSINO...,1002,1002-1...,0,NOV_EN...,M,40,0,SL-09,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,30,6
2,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,0002.61,NOVO E...,1,ENSINO...,1003,1003-1...,0,NOV_EN...,N,39,0,SL-01,ESTADUAL,COMPLETA,4,45,N,Próprio,Não,30,6
3,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,0023.24,NEM IT...,3,ENSINO...,IF_PSC...,IF_PSC...,0,NEM_IF...,M,35,0,SL-05,ESTADUAL,COMPLETA,10,50,N,Próprio,Sim,30,6
4,BAIXAD...,ARARUAMA,33026394,118023...,CIEP 4...,0023.38,NEM IT...,3,ENSINO...,IF_GDI...,IF_GDI...,0,NEM_IF...,N,28,0,SL-09,ESTADUAL,COMPLETA,2,45,N,Próprio,Sim,30,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12503,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,0002.84,ENSINO...,1,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,33,0,SL-02,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,46,10
12504,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,0002.84,ENSINO...,1,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,35,0,SL-03,ESTADUAL,COMPLETA,4,50,N,Próprio,Não,46,10
12505,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,0002.84,ENSINO...,2,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,23,0,SL-05,ESTADUAL,COMPLETA,0,50,N,Próprio,Não,46,10
12506,SUL FL...,VOLTA ...,33103097,118023...,CIEP 4...,0002.84,ENSINO...,3,NEM IT...,NEM_CI...,NEM_CI...,0,EMI_IT...,I,22,0,SL-06,ESTADUAL,COMPLETA,4,50,N,Próprio,Sim,46,10
TOTAL,NaN,NaN,NaN,147611...,NaN,NaN,NaN,24325,NaN,NaN,NaN,81,NaN,NaN,362328,5757,NaN,NaN,NaN,57687,616120,NaN,NaN,NaN,400868,83228

In [ ]:
df_alvo = df_selecionado.groupby('CENSO').agg({'REGIONAL': 'first', 'MUNICÍPIO': 'first', 'CENSO': 'first', 'ESCOLA': 'first', 'TOTAL DE ALUNOS': 'sum'})
display(df_alvo)
df_alvo.to_excel("df_alvo.xlsx", index=False)

           REGIONAL  MUNICÍPIO     CENSO     ESCOLA  TOTAL DE ALUNOS
CENSO
33000026  NOROES...  BOM JE...  33000026  CE GOV...         63
33000042  NOROES...  BOM JE...  33000042  CE PAD...         60
33000115  NOROES...  BOM JE...  33000115  CE ALC...         31
33000158  NOROES...  BOM JE...  33000158  CE EUC...        276
33000360  NOROES...  BOM JE...  33000360  IE EBE...        355
...             ...        ...       ...        ...        ...
33439222  METROP...  RIO DE...  33439222  CE COM...        596
33507210  METROP...  SÃO GO...  33507210  CE COM...        252
33508232  METROP...  RIO DE...  33508232  CE JOR...        326
33518238  METROP...  SÃO GO...  33518238  CIEP 5...         85
33558230  METROP...  RIO DE...  33558230  CE DEP...       1069

[859 rows x 5 columns]

In [ ]:
df_eliminados = df_exclusao.groupby('CENSO').agg({'REGIONAL': 'first', 'MUNICÍPIO': 'first', 'CENSO': 'first', 'ESCOLA': 'first', 'TOTAL DE ALUNOS': 'sum'})
display(df_eliminados)
df_eliminados.to_excel("df_eliminados.xlsx", index=False)

           REGIONAL  MUNICÍPIO     CENSO     ESCOLA  TOTAL DE ALUNOS
CENSO
33000026  NOROES...  BOM JE...  33000026  CE GOV...        230
33000042  NOROES...  BOM JE...  33000042  CE PAD...        112
33000115  NOROES...  BOM JE...  33000115  CE ALC...         76
33000158  NOROES...  BOM JE...  33000158  CE EUC...        345
33000360  NOROES...  BOM JE...  33000360  IE EBE...        377
...             ...        ...       ...        ...        ...
33518211  NOROES...  SANTO ...  33518211  CE PED...        239
33518220  NOROES...  BOM JE...  33518220  CE LUI...         79
33518238  METROP...  SÃO GO...  33518238  CIEP 5...        207
33558221  BAIXAD...  SAQUAREMA  33558221  CE ISM...        247
33558230  METROP...  RIO DE...  33558230  CE DEP...       1257

[1148 rows x 5 columns]